apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devsecops-demo-pdb
  namespace: demo
  labels:
    app.kubernetes.io/name: devsecops-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devsecops-demo
