apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: devsecops-demo
  namespace: demo
spec:
  serviceRef:
    name: devsecops-demo
    port: 80
  targetGroupARN: "${TARGET_GROUP_ARN}"
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: "${ALB_SECURITY_GROUP_ID}"
        ports:
          - protocol: TCP
            port: 8080
